accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * #ALL
from django.contrib.auth.models import User

app_name = 'accounts'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),
    url(r'^sign_in/$', sign_in, name='sign_in'),
    url(r'^api/register_user$', register_user, name='register_user'),
    url(r'^upload_track/$', upload_track_page, name='upload_track_page'),
    url(r'^api/upload_track/$', upload_track, name='upload_track'),
    url(r'^api/getplaylist/$', getplaylist, name='getplaylist'),

]

albums/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * 
from django.contrib.auth.models import User

app_name = 'albums'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),
    url(r'^sign in/$', sing in, name='sign in'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include("accounts.urls", namespace='accounts')),
]

playlist/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * 
from django.contrib.auth.models import User

app_name = 'playlist'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),  
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    ProfileModel = instance.__class__
    if ProfileModel.objects.order_by("id").last():
        new_id = ProfileModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)
 
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE,related_name='profile')
    name = models.TextField(blank = True,null = True,default='name')
    mail = models.TextField(blank = True,null = True,default='mail')
    image = models.ImageField(upload_to=upload_location, blank = True,null = True)

albums/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    AlbumModel = instance.__class__
    if AlbumModel.objects.order_by("id").last():
        new_id = AlbumModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)

class Album(models.Model):
    name = models.TextField(blank = True,null = True,default='name')
    description = models.TextField(blank = True,null = True,default='mail')
    image = models.ImageField(upload_to=upload_location, blank = True,null = True)

playlist/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    ProfileModel = instance.__class__
    if ProfileModel.objects.order_by("id").last():
        new_id = ProfileModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)
 
class Playlist(models.Model):
    name = models.TextField(blank = True,null = True,)
    image = models.ImageField(upload_to=upload_location, blank = True,null = True,)
    listenings = models.IntegerField(blank = True,null = True,)


class Track(models.Model):
    name = models.TextField(blank = True,null = True,default='My Playlist')
    artist = models.TextField(blank = True,null = True,default='My Playlist')
    listenings = models.IntegerField(blank = True,null = True,default=0)
    file = models.FileField(default='')

accounts/views.py
from django.shortcuts import render
from django.http import JsonResponse
from playlist.models import Playlist
from playlist.models import Playlist, Track

def main(request):
    context = {
    }
    return render(request, "main.html", context)
    
def about(request):
    context = {
        "id": 6,
    }
    return render(request, "playlist.html", context)

def sign_in(request):
    context = {
        "id": 6,
    }
    return render(request, "sign_in.html", context)


def register_user(request):
    name = request.GET.get("mail")
    Playlist.objects.create(name=name)
    data = {
    }
    return JsonResponse(data)

def upload_track_page(request):
    context = {
    }
    return render(request, "create_track.html", context)

def upload_track(request):
    song_name = request.POST.get("song_name")
    print(song_name)
    artist = request.POST.get("artist")
    
    
    track = Track.objects.create(
        name=song_name,
        artist=artist,        )
    if request.FILES.get('file'):
        track.file = request.FILES.get('file')
        track.save()
    data = {
        "ok":"VSE POLUCHILOSЬ"
    }
    return JsonResponse(data)

def getplaylist(request):
    tracks = Track.objects.all()
    data_music = []
    for i in range(0, len(tracks)):
        track = tracks[i]
        data_music.append([
            track.artist, 
            track.name, 
            track.file.url
             ])
    data = {
        "data_music":data_music,
    }
    return JsonResponse(data)

albums/views.py
from django.shortcuts import render

def main(request):
    like = 0
    like = like + 1
    context = {
        "land_type":"about",
        "name": "arsen",
        "id": 6,
    }
    return render(request, "index.html", context)
    
def about(request):
    context = {
        "id": 6,
    }
    return render(request, "about.html", context)
    

playlist/views.py
from django.shortcuts import render

from rest_framework.views import APIView 
from rest_framework.response import Response 
from rest_framework import authentication, permissions 
from django.http import JsonResponse

def main(request):
    like = 0
    like = like + 1
    context = {
        "land_type":"about",
        "name": "arsen",
        "id": 6,
    }
    return render(request, "index.html", context)
    
def about(request):
    context = {
        "id": 6,
    }
    return render(request, "playlist.html", context)
    

frontend/templates/header.html
<link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

<input class="menu-icon" type="checkbox" id="menu-icon" name="menu-icon"/>
<label for="menu-icon"></label>
<nav class="nav">
	<ul>
		<li><a href="{% url 'accounts:main' %}">Home</a></li>
		<li><a href="{% url 'accounts:sign_in' %}">Sign_in</a></li>
	</ul>
</nav>




frontend/templates/index.html
{% load static %}

<html>
<head>
	<title>NisCE</title>
<!-- 	<link rel="stylesheet" type="text/css" href="style/style.css">
 -->    
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Gloria+Hallelujah&family=Merienda&family=Satisfy&display=swap" rel="stylesheet">
</head>
<body>
	{% include 'header.html' %}
	{% block content %}{% endblock content %}
	<span style="display:none" csrf="{{ csrf_token }}" id="csrftoken"></span>



<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script> 

</body>
</html>

frontend/templates/main.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="section-center">
  <h1 class="mb-0">Welcome</h1>
</div>

{% endblock content %}

frontend/templates/sign_in.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<section class="forms-section">
    <h1 class="section-title">NIS Strangers</h1>
    <div class="forms">
        <div class="form-wrapper is-active">
            <button type="button" class="switcher switcher-login">
                Login
                <span class="underline"></span>
            </button>
            <form class="form form-login">
                <fieldset>
                    <legend>Please, enter your email and password for login.</legend>
                    <div class="input-block">
                        <label for="login-email">E-mail</label>
                        <input id="login-email" type="email" required>
                    </div>
                    <div class="input-block">
                        <label for="login-password">Password</label>
                        <input id="login-password" type="password" required>
                    </div>
                </fieldset>
                <button type="submit" class="btn-login">Login</button>
            </form>
        </div>
        <div class="form-wrapper">
            <button type="button" class="switcher switcher-signup">
                Sign Up
                <span class="underline"></span>
            </button>
            <form class="form form-signup">
                <fieldset>
                    <legend>Please, enter your email, password and password confirmation for sign up.</legend>
                    <div class="input-block">
                        <label for="signup-email">E-mail</label>
                        <input id="signup-email" type="email" required>
                    </div>
                    <div class="input-block">
                        <label for="signup-password">Password</label>
                        <input id="signup-password" type="password" required>
                    </div>
                    <div class="input-block">
                        <label for="signup-password-confirm">Confirm password</label>
                        <input id="signup-password-confirm" type="password" required>
                    </div>
                </fieldset>
                <button type="submit" class="btn-signup">Continue</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}